name: 'Test Report'
on:
  workflow_run:
    workflows: ['Java CI with Maven']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: phoenix-actions/test-reporting@v8
        id: test-report                     # Set ID reference for step
        with:
          artifact: Package           # artifact name
          name: JEST Tests                  # Name of the check run which will be created
          path: github-actions-1.0-SNAPSHOT.jar                    # Path to test results (inside artifact .zip)
          reporter: jest-junit              # Format of test results